### ISSUE TITLE
Failure to save font imported from XML

### ISSUE THREAD

**Issue by khaledhosny** [behdad/fonttools#298]
Doing something like:

```
from fontTools.ttLib import TTFont
f = TTFont("Roboto-Regular.ttf")
f.saveXML("r.ttx")
x = TTFont()
x.importXML("r.ttx")
x.saveXML("r2.ttx")
```
Will fail with:
```
Traceback (most recent call last):
  File "a.py", line 7, in <module>
    x.saveXML("r2.ttx")
  File "/fonttools/Lib/fontTools/ttLib/__init__.py", line 283, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "/fonttools/Lib/fontTools/ttLib/__init__.py", line 323, in _tableToXML
    table.toXML(writer, self)
  File "/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 108, in toXML
    self.table.toXML2(writer, font)
  File "/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 666, in toXML2
    value = getattr(self, conv.name)
  File "/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 528, in __getattr__
    raise AttributeError(attr)
AttributeError: AttachList
```
While dumping `GDEF` table, but even if this table is skipped it will fail in a similar way with `GPOS`. Does not seem to be a font-specific issue.

**Comment by anthrotype** [comment]
@khaledhosny yes, that is a known issue: https://github.com/behdad/fonttools/issues/141
I don't know how to fix that yet.

**Comment by khaledhosny** [comment]
I see, closing as duplicate then. Thanks.

**Comment by behdad** [comment]
Thanks.  I'll try to fix this.
