### ISSUE TITLE
pyftmerge error when merging some Not fonts

### ISSUE THREAD

**Issue by khaledhosny** [behdad/fonttools#322]
I’m trying to merge Noto Serif into Noto Naskh Arabic, but `pyftmerge NotoNaskhArabic-Regular.ttf NotoSerif-Regular.ttf ` fails with:
````
Traceback (most recent call last):
  File "pyftmerge", line 9, in <module>
    load_entry_point('fonttools==2.5', 'console_scripts', 'pyftmerge')()
  File "/fonttools/Lib/fontTools/merge.py", line 940, in main
    font = merger.merge(args)
  File "/fonttools/Lib/fontTools/merge.py", line 770, in merge
    table = clazz(tag).merge(self, tables)
  File "/fonttools/Lib/fontTools/merge.py", line 374, in merge
    assert m.duplicateGlyphsPerFont[fontIdx].get(oldgid, gid) == gid
AssertionError
````

But if I reverse the order, i.e. `pyftmerge NotoSerif-Regular.ttf NotoNaskhArabic-Regular.ttf`, it works just fine.

**Comment by davelab6** [comment]
I also found this when working with a myanmar/Latin pair, in
github.com/khmertype/Gantgaw
