### ISSUE TITLE
TTX and subset crashes on Palatino Linotype (Windows)

### ISSUE THREAD

**Issue by Ziriax** [behdad/fonttools#323]
Converting the pala.ttf bundled  with Microsoft Windows to ttx works fine.

Converting it back to a TTF crashes (see first log below).

```
Compiling "c:\temp\pala.ttx" to "c:\temp\pala.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'LTSH' table...
Parsing 'VDMX' table...
Parsing 'hdmx' table...
Parsing 'cmap' table...
Parsing 'fpgm' table...
Parsing 'prep' table...
Parsing 'cvt ' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Traceback (most recent call last):
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttx.py", line 342, in main
    process(jobs, options)
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttx.py", line 325, in process
    action(input, output, options)
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttx.py", line 236, in ttCompile
    ttf.importXML(input, quiet=options.quiet)
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\__init__.py", line 352, in importXML
    reader.read()
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\misc\xmlReader.py", line 30, in read
    self._parseFile(file)
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\misc\xmlReader.py", line 42, in _parseFile
    chunk = file.read(BUFSIZE)
  File "C:\bin\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4281: character maps to <undefined>
(Hit any key to exit)
```

The subsetting tool also crashes on that font with another error:

```
Traceback (most recent call last):
  File "C:\bin\Python34\Scripts\pyftsubset-script.py", line 9, in <module>
    load_entry_point('fonttools==2.5', 'console_scripts', 'pyftsubset')()
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\subset.py", line 2738, in main
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\subset.py", line 2611, in save_font
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\__init__.py", line 224, in save
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\__init__.py", line 639, in _writeTable
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\__init__.py", line 652, in getTableData
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 86, in compile
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 242, in getAllData
  File "C:\bin\Python34\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 264, in getDataLength
AttributeError: 'OTTableWriter' object has no attribute 'longOffset'
```

**Comment by Ziriax** [comment]
The second subsetting issue seems to be fixed by adding the following line to the OTTableWriter constructor (but I'm not sure if this is correct at all, at least the subsetter completes without error, and I get an output TTF that I can open)

``` Python
	def __init__(self, globalState, localState=None):
		self.items = []
		self.pos = None
		self.globalState = globalState
		self.localState = localState
		self.parent = None
		# the line below fixes the subsetter crash
		self.longOffset = False
```

**Comment by anthrotype** [comment]
@Ziriax thanks for reporting this. Could you please try to see if this fixes the UnicodeDecodeError issue when decompiling Palatino Linotype using Python 3 on Windows?

https://github.com/behdad/fonttools/pull/324

**Comment by anthrotype** [comment]
what's the exact command line that you used with pyftsubset which raised the `AttributeError` above?

**Comment by Ziriax** [comment]
The command line for the pyftsubset was just ```pala.ttf --unicodes=*```. But it does not matter what Unicode range I provide

**Comment by Ziriax** [comment]
I just tested this at home (Windows 8.1), and neither TTX nor pyftsubset crashed here... I will investigate further.

**Comment by Ziriax** [comment]
The bugs occurs only with ```pala.ttf``` version ```1.4```, [the one from Windows XP](https://www.microsoft.com/typography/fonts/font.aspx?FMID=854)

The UTF-8 patch e24f2eabceaa11d0b5fe0cf2e18d4cf5002faa96 does not seem to fix this.

The command line with the smallest unicode range that I could find that crashes ```pyftsubset``` is

```pyftsubset pala.ttf --unicodes="U+0052-0056"```

The verbose log of that invocation of ```pyftsubset``` is

```
Text: ''
Unicodes: [82, 83, 84, 85, 86]
Glyphs: []
Gids: []
maxp pruned
LTSH dropped
cmap pruned
glyf pruned
kern dropped
name pruned
post pruned
PCLT dropped
BASE dropped
GPOS pruned
GSUB pruned
JSTF dropped
DSIG dropped
Added gid0 to subset
Closing glyph list over 'GSUB': 6 glyphs before
Glyph names: ['.notdef', 'R', 'S', 'T', 'U', 'V']
Glyph IDs:     [0, 20, 21, 22, 23, 24]
Closed glyph list over 'GSUB': 7 glyphs after
Glyph names: ['.notdef', 'R', 'S', 'T', 'U', 'V', 'glyph00274']
Glyph IDs:     [0, 20, 21, 22, 23, 24, 274]
Closing glyph list over 'glyf': 7 glyphs before
Glyph names: ['.notdef', 'R', 'S', 'T', 'U', 'V', 'glyph00274']
Glyph IDs:     [0, 20, 21, 22, 23, 24, 274]
Closed glyph list over 'glyf': 7 glyphs after
Glyph names: ['.notdef', 'R', 'S', 'T', 'U', 'V', 'glyph00274']
Glyph IDs:     [0, 20, 21, 22, 23, 24, 274]
Retaining 7 glyphs: 
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
VDMX subsetting not needed
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
glyf subsetted
name subsetting not needed
post subsetted
gasp subsetting not needed
GDEF subsetted
GPOS subsetted
GSUB subsetted
glyf pruned
GDEF pruned
GPOS pruned
GSUB pruned

Traceback (most recent call last):
  File "P:\app\Python-3.4.3\Scripts\pyftsubset-script.py", line 9, in <module>
    load_entry_point('fonttools==2.5', 'console_scripts', 'pyftsubset')()
  File "P:\app\Python-3.4.3\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\subset.py", line 2738, in main
  File "P:\app\Python-3.4.3\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\subset.py", line 2611, in save_font
  File "P:\app\Python-3.4.3\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\__init__.py", line 224, in save
  File "P:\app\Python-3.4.3\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\__init__.py", line 639, in _writeTable
  File "P:\app\Python-3.4.3\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\__init__.py", line 652, in getTableData
  File "P:\app\Python-3.4.3\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 86, in compile
  File "P:\app\Python-3.4.3\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 242, in getAllData
  File "P:\app\Python-3.4.3\lib\site-packages\fonttools-2.5-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 264, in getDataLength
AttributeError: 'OTTableWriter' object has no attribute 'longOffset'
```

**Comment by Ziriax** [comment]
According to [this](https://bz.apache.org/ooo/show_bug.cgi?id=27336) the Palatino version 1.40 contains some bugs... Anyway, it would be nice if the tool did not crash, even for buggy fonts, although I do understand this can be difficult to achieve

**Comment by anthrotype** [comment]
@Ziriax it should be fixed now. Please check, thanks.
