### ISSUE TITLE
traceback.print_exc(file) fails on Python 3 when file = BytesIO()

### ISSUE THREAD

**Issue by anthrotype** [behdad/fonttools#328]
whenever a table decompilation fails, for any reason, the normal behaviour is to retain the binary table data and fall back to the `DefaultTable`. The `traceback` module is used to print the error to a `StringIO` stream in order to save that message in a table attribute.

The problem is that in Python3, the `traceback.print_exc(file)` expects a stream of *unicode* text, but instead it's receiving a stream of *bytes*. This is because, when running fontTools under Python 3, the `StringIO` class, as imported from `fontTools.misc.py23`, is actually an alias of `io.BytesIO`.

This specific issue  could be easily fixed by simply importing the *true* `io.StringIO`, which represents an in-memory stream of unicode text, just before calling  `traceback.print_exc(file)`:

However, maybe we should consider modifying the `py23` bridge itself, so that all references to `StringIO` in the codebase will actually mean `io.BytesIO` on __both__ Python 2 and 3; and use the name `StringIO` (from `io` module) to mean a stream of unicode text on both 2 and 3. 

Here's the traceback of `traceback`: 
```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/fonttools3/bin/ttx", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/cosimolupo/Documents/Github/fonttools/Tools/ttx", line 6, in <module>
    ttx.main(sys.argv[1:])
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttx.py", line 323, in main
    process(jobs, options)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttx.py", line 308, in process
    action(input, output, options)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttx.py", line 217, in ttDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 283, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 298, in _tableToXML
    table = self[tag]
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 404, in __getitem__
    traceback.print_exc(file=file)
  File "/usr/local/var/pyenv/versions/3.4.3/lib/python3.4/traceback.py", line 252, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/local/var/pyenv/versions/3.4.3/lib/python3.4/traceback.py", line 170, in print_exception
    print(line, file=file, end="")
TypeError: 'str' does not support the buffer interface

**Comment by behdad** [comment]
Lets change py23 to have BytesIO and UnicodeIO, and not use StringIO in the codebase at all...

**Comment by anthrotype** [comment]
OK, but the name `UnicodeIO` does not exist in the `io` module, neither on Python 2 nor 3.
That's why I proposed to use `BytesIO` for bytes, and `StringIO` (in the Python 3 sense) for unicode strings.
But if you like `UnicodeIO` name, we could add an alias for it in `py23`.

**Comment by behdad** [comment]
I was suggesting that we add an alias, just to disambiguate it eternally.

**Comment by anthrotype** [comment]
Agreed. I'll do that shortly.

**Comment by anthrotype** [comment]
well, it turns out sometimes we do need to use `StringIO` in a version-specific sense, at least for this particular case.
As I said, If we use bytes, `traceback.print_exc` will fail in Python 3; however, if we use unicodes, then Python 2 in turn will fail!

```python
>>> import traceback
>>> from io import StringIO as UnicodeIO
>>> file = UnicodeIO()
>>> try:
...     raise Exception(":_(")
... except:
...     traceback.print_exc(file=file)
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/traceback.py", line 233, in print_exc
    print_exception(etype, value, tb, limit, file)
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
TypeError: unicode argument expected, got 'str'
```

Hence my PR #330.

**Comment by behdad** [comment]
Thanks!
