### ISSUE TITLE
TTX finds an error in a font's GSUB table that no other tools see

### ISSUE THREAD

**Issue by Pomax** [behdad/fonttools#415]
I'm generating a test font over on, http://pomax.github.io/simple-cff-builder, with GSUB ligatures for "ABC" => "a" (technically a glyph called "alphabet", but it's getting stored in a cmap at a spot that belongs to "a") and "RECTANGLE" => "r" (technically "rectangle" - it ends up on "r").

If I generate this with only one substitution, so either "ABC" or "RECTANGLE", everything works fine, but with both substitutions turned on, the GSUB table is apparently incorrect: TTX claims the following:

```
<GSUB ERROR="decompilation error">
  <!-- An error occurred during the decompilation of this table -->
  <!-- Traceback (most recent call last):
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\__init__.py", line 390, in __getitem__
           table.decompile(data, self)
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otBase.py", line 44, in decompile
           self.table.decompile(reader, font)
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otBase.py", line 568, in decompile
           table[conv.name] = conv.read(reader, font, table)
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otConverters.py", line 245, in read
           table.decompile(reader, font)
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otBase.py", line 563, in decompile
           l.append(conv.read(reader, font, table))
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otConverters.py", line 245, in read
           table.decompile(reader, font)
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otBase.py", line 563, in decompile
           l.append(conv.read(reader, font, table))
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otConverters.py", line 245, in read
           table.decompile(reader, font)
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otBase.py", line 572, in decompile
           self.postRead(table, font)
         File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\otTables.py", line 409, in postRead
           assert len(input) == len(ligSets)
       AssertionError
        -->
  <hexdata>
    00010000 000a0024 00320002 44464c54
    000e6c61 746e000e 00040000 0000ffff
    00010000 00016c69 67610008 00000001
    00000001 00040004 00000001 00080001
    00080001 00180002 00020001 00010000
    00120012 00010002 0006000e 001a0003
    00020003 001b0009 00050003 00140001
    000e0007 000c0005  
  </hexdata>
</GSUB>
```

But OTS sees nothing wrong, the new MS Font Validator sees nothing wrong, and ADOFDK's `spot` sees nothing wrong. Is there a way to have TTX be more detailed about what it *was* able to parse until it hit an error? It would be *super* helpful to see the part of the GSUB data it was able to parse, so that it's more obvious where the error could be.

(I had a look at the bytecode for the GSUB table, and honestly, it looks fine... but then the gh-pages site shows that only one of the two substitutions actually works, and TTX crashes, so things are clearly not *actually* fine)

**Comment by anthrotype** [comment]
Can you post the bytecode of your GSUB table so we can try debugging the issue?

**Comment by anthrotype** [comment]
Oh sorry, I see it's there already. Somehow it wasn't there in the email :)

**Comment by behdad** [comment]
Looks like you failed to correctly sort the ligatures by their first glyph.  At least, that's what the error means, and that's why one doesn't work.  Let me look at the bytecode now.

**Comment by behdad** [comment]
Technically speaking this is not an error.  But it definitely shows a badly-constructed font.

**Comment by behdad** [comment]
Indeed, your coverage covers two glyphs (0x01 and 0x12), but your LigSetCount is one.

**Comment by behdad** [comment]
If you remove the assert, it should decompile fine.  I'm fine turning this into a warning.

**Comment by Pomax** [comment]
Oh man, thanks. It looks like the code's indeed not generating separate LigatureSets for the two targets, but simply overloads a single set. Time to fix that, and thanks in advance for the TTX fine tuning!

**Comment by Pomax** [comment]
Fixed the Sets issue, and every works as expected now. Thanks for the help!
