### ISSUE TITLE
TTX failure on Yosemite (OSX 10.10.5)

### ISSUE THREAD

**Issue by EbenSorkin** [behdad/fonttools#439]
I have a failure to dump but I can't interpret the feedback I see to sort out what to do. E.g. Is it a bug or do I need to install a dependency to resolve this or some other thing.

Here is a text sample. The feedback does not appear to vary with the font. So far I have only thrown TTF files not OTF files at it.

If I can supply more information to help please let me know.

In the meantime I would like to find a rapid workaround. I was thinking of trying an older version of TTX. Any other suggestions are most welcome!

Terminal transcript below
------

Macintosh:~ leihamaldonado$ ttx /Users/leihamaldonado/Documents/LobsterThai-Regular.ttf 

Traceback (most recent call last):

  File "/usr/local/bin/ttx", line 9, in <module>

    load_entry_point('fonttools==3.0', 'console_scripts', 'ttx')()

  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 352, in main

    jobs, options = parseOptions(args)

  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 306, in parseOptions

    tp = guessFileType(input)

  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttx.py", line 268, in guessFileType

    cr, tp = getMacCreatorAndType(fileName)

  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/misc/macCreatorType.py", line 23, in getMacCreatorAndType

    finderInfo = xattr.getxattr(path, 'com.apple.FinderInfo')

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/xattr/__init__.py", line 186, in getxattr

    return xattr(f).get(attr, options=symlink and XATTR_NOFOLLOW or 0)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/xattr/__init__.py", line 84, in get

    return self._get(name, 0, 0, options | self.options)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/xattr/__init__.py", line 28, in _func

    return func(first, *args)

KeyError: 'com.apple.FinderInfo'

Macintosh:~ leihamaldonado$

**Comment by anthrotype** [comment]
Hi @EbenSorkin,

This issue should have been fixed with commit https://github.com/behdad/fonttools/commit/f10cb1f17ddea86c9aec4ba4788243a25fb50095

You can try to fetch the latest master's HEAD. We'll tag a new 3.1 release soon

Let us know if this doesn't solve it for you.

**Comment by EbenSorkin** [comment]
How do I  fetch the latest master's HEAD? If you give me a step by step process I promise to carefully follow it.

**Comment by twardoch** [comment]
Just download and unzip [this repo's master zip](https://github.com/behdad/fonttools/archive/master.zip) and then run `sudo python setup.py install` as you would normally do.

**Comment by anthrotype** [comment]
Adam beat me ;)

If you wish to use git to download the source code, you can clone the repository by doing:
```
$ git clone https://github.com/behdad/fonttools
```
Or, if you have already cloned it in the past, change directory to where you have cloned it, e.g. `cd fonttools`, and then do `git checkout master` to set the local active branch to `master`, and `git pull` to synchronize it with its remote counterpart.

**Comment by EbenSorkin** [comment]
Thank you!

-e.

**Comment by EbenSorkin** [comment]
Thank to you both!

That worked.

:-)

Dancing ensues...

-e.
