### ISSUE TITLE
[feaLib] support the inline feature keyword

### ISSUE THREAD

**Issue by adrientetar** [behdad/fonttools#441]
Given the following feature file:

```
languagesystem DFLT dflt;

feature aalt {
    feature sups;
} aalt;

feature sups {
    sub one by onesuperior;
    sub two by twosuperior;
    sub three by threesuperior;
} sups;
```

I get the following traceback:

```
warning: unnamed anchor discarded in section
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\fontView.py", line 900, in exportFile
    otf = compileOTF(self.font)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 32, in compileOTF
    featureCompilerClass, kernWriter, markWriter)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 18, in _compile
    feasrc = featureCompiler.compile()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 28, in compile
    self.setupFile_featureTables()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 166, in setupFile_featureTables
    addOpenTypeFeatures(fea_path, self.outline)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 12, in addOpenTypeFeatures
    builder.build()
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 37, in build
    self.parseTree = Parser(self.featurefile_path).parse()
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\parser.py", line 41, in parse
    statements.append(self.parse_feature_block_())
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\parser.py", line 660, in parse_feature_block_
    self.parse_block_(block, vertical)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\parser.py", line 702, in parse_block_
    self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: C:\Users\Admin\AppData\Local\Temp\tmpr4rwelbj:4:5: Expected glyph class definition or statement
```

i.e. the inline feature keyword in `aalt` isn't supported, see [Section 8.a](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#8.a) of the spec.

cc @brawer

**Comment by brawer** [comment]
Done; implemented `feature aalt` in 2de6fc7744ce000f344ff4ecbb528b6d0c0dbd25.

**Comment by adrientetar** [comment]
:+1:

**Comment by adrientetar** [comment]
@brawer Given feature file:

```
# Prefix: Languagesystems
# automatic
languagesystem DFLT dflt;

feature aalt {
# automatic
feature sups;
feature frac;
feature ordn;
} aalt;

feature sups {
# automatic
sub one by onesuperior;
sub two by twosuperior;
sub three by threesuperior;
} sups;

feature frac {
# automatic
sub one slash four by onequarter;
sub one slash two by onehalf;
sub three slash four by threequarters;
} frac;

feature ordn {
# automatic
sub [zero one two three four five six seven eight nine] [A a]' by ordfeminine;
sub [zero one two three four five six seven eight nine] [O o]' by ordmasculine;
} ordn;

feature liga {
# automatic
sub f i by fi;
sub f l by fl;
} liga;
```

I get traceback:

```
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\scriptingWindow.py", line 40, in runScript
    exec(code, global_vars)
  File "<string>", line 6, in <module>
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 29, in compileOTF
    featureCompilerClass, kernWriter, markWriter)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 18, in _compile
    featureCompiler.compile()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 27, in compile
    self.setupFile_featureTables()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 166, in setupFile_featureTables
    addOpenTypeFeatures(fea_path, self.outline)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 13, in addOpenTypeFeatures
    builder.build()
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 48, in build
    self.build_feature_aalt_()
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 112, in build_feature_aalt_
    location)
fontTools.feaLib.error.FeatureLibError: Feature aalt has not been defined
```

Any idea?

(By the way, it would be nice if error message could tell which line the error occured on.)

**Comment by brawer** [comment]
I’m looking into it, thanks for the report. Regarding the line, class FeatureLibError has a `location` attribute which is a tuple of (fileName, line, column).

**Comment by adrientetar** [comment]
> Regarding the line, class FeatureLibError has a location attribute which is a tuple of (fileName, line, column).

Great! Thanks.

**Comment by brawer** [comment]
Thanks for the report; fixed. Your sample snippet is now a test case.

**Comment by adrientetar** [comment]
Thanks. A great honor!
