### ISSUE TITLE
[feaLib] contextual substitution not fully handled

### ISSUE THREAD

**Issue by jamesgk** [behdad/fonttools#445]
feaLib handles the OTF spec's first example for contextual substitution, but raises an AssertionError on the other ones. E.g. adding this rule to testdata/spec5fi1.fea:

```
substitute [a e n] d' by d.alt;
```

yields the following result:

```
======================================================================
FAIL: test_substitute_lookups (__main__.ParserTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "parser_test.py", line 793, in test_substitute_lookups
    doc = Parser(self.getpath("spec5fi1.fea")).parse()
  File "/usr/local/google/home/jamesgk/code/fonttools/Lib/fontTools/feaLib/parser.py", line 41, in parse
    statements.append(self.parse_feature_block_())
  File "/usr/local/google/home/jamesgk/code/fonttools/Lib/fontTools/feaLib/parser.py", line 660, in parse_feature_block_
    self.parse_block_(block, vertical)
  File "/usr/local/google/home/jamesgk/code/fonttools/Lib/fontTools/feaLib/parser.py", line 694, in parse_block_
    statements.append(self.parse_substitute_())
  File "/usr/local/google/home/jamesgk/code/fonttools/Lib/fontTools/feaLib/parser.py", line 547, in parse_substitute_
    assert len(new) == 0, new
AssertionError: [frozenset([u'd.alt'])]
```

**Comment by adrientetar** [comment]
I got the same oops in a frac feature.

**Comment by brawer** [comment]
Re-opening for the other GSUB types.

**Comment by anthrotype** [comment]
:+1:
