### ISSUE TITLE
[feaLib] heterogenous kerning not supported in a lookup

### ISSUE THREAD

**Issue by adrientetar** [behdad/fonttools#456]
I have a lookup that looks like this:

```
lookup latnKern {
    pos v v 14;
    subtable;
    @kc26_first_1 = [D O Q];
    @kc26_second_2 = [T V W];
    pos @kc26_first_1 @kc26_second_2 -26;
} latnKern;

feature kern {
    lookup latnKern;
} kern;
```

I get the following traceback on the class kerning declaration:

```
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\representationFactories\openTypeFactory.py", line 5, in TTFontFactory
    otf = compileOTF(font)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 29, in compileOTF
    featureCompilerClass, kernWriter, markWriter)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 18, in _compile
    featureCompiler.compile()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 27, in compile
    self.setupFile_featureTables()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 166, in setupFile_featureTables
    addOpenTypeFeatures(fea_path, self.outline)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 13, in addOpenTypeFeatures
    builder.build()
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 49, in build
    self.parseTree.build(self)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\ast.py", line 79, in build
    s.build(builder)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\ast.py", line 108, in build
    Block.build(self, builder)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\ast.py", line 79, in build
    s.build(builder)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\ast.py", line 441, in build
    self.glyphs2.glyphSet(), self.valuerecord2)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 665, in add_class_pair_pos
    lookup = self.get_lookup_(location, ClassPairPosBuilder)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\feaLib\builder.py", line 89, in get_lookup_
    "the same lookup type and flag", location)
fontTools.feaLib.error.FeatureLibError: C:\Users\Admin\AppData\Local\Temp\tmpnzy84mqf:938:5: Within a named lookup block, all rules must be of the same lookup type and flag
```

However, given that it is declared after a subtable statement, the use of different lookup should be allowed here I believe.

cc @brawer

**Comment by adrientetar** [comment]
If I inline the lookup, the error disappears.

**Comment by itmard** [comment]
me too

**Comment by behdad** [comment]
@brawer can you prioritize this please?  Thanks.

**Comment by anthrotype** [comment]
:+1
