### ISSUE TITLE
[feaLib] Support CID representation

### ISSUE THREAD

**Issue by mashabow** [behdad/fonttools#459]
Currently, `feaLib.Lexer` supports CID representation but `feaLib.Parser` doesn't:

```
$ cat test.fea
feature test {
    sub \1 by \2;
} test;

$ python
Python 2.7.11 (default, Dec 16 2015, 11:56:37)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fontTools.feaLib.parser import Parser
>>> Parser('test.fea').parse()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mnakamura/repos/fonttools/Lib/fontTools/feaLib/parser.py", line 41, in parse
    statements.append(self.parse_feature_block_())
  File "/Users/mnakamura/repos/fonttools/Lib/fontTools/feaLib/parser.py", line 776, in parse_feature_block_
    self.parse_block_(block, vertical)
  File "/Users/mnakamura/repos/fonttools/Lib/fontTools/feaLib/parser.py", line 828, in parse_block_
    statements.append(self.parse_substitute_())
  File "/Users/mnakamura/repos/fonttools/Lib/fontTools/feaLib/parser.py", line 505, in parse_substitute_
    old_prefix, old, lookups, old_suffix = self.parse_glyph_pattern_()
  File "/Users/mnakamura/repos/fonttools/Lib/fontTools/feaLib/parser.py", line 236, in parse_glyph_pattern_
    gc = self.parse_glyphclass_(accept_glyphname=True)
  File "/Users/mnakamura/repos/fonttools/Lib/fontTools/feaLib/parser.py", line 189, in parse_glyphclass_
    self.expect_symbol_("[")
  File "/Users/mnakamura/repos/fonttools/Lib/fontTools/feaLib/parser.py", line 903, in expect_symbol_
    self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: test.fea:2:9: Expected '['
```

Are there any plans to support CID representation? It is essential to develop CJK fonts.

You can find actual examples of feature files in [adobe-fonts/source-han-sans](https://github.com/adobe-fonts/source-han-sans), such as [Regular/features.JP](https://github.com/adobe-fonts/source-han-sans/blob/master/Regular/features.JP).

**Comment by brawer** [comment]
Thanks for the report! CIDs should now be handled; just pushed a fix. It will take a bit until feaLib can process the feature file for Source Han Sans, but I’m working on adding support for the remaining tables.

**Comment by mashabow** [comment]
Thank you!
