### ISSUE TITLE
Error exporting OTF

### ISSUE THREAD

**Issue by aaronbell** [behdad/fonttools#463]
I'm using the [FontMake](https://github.com/googlei18n/fontmake) package to convert https://github.com/Microsoft/Selawik to binary files. However, I run into an error:

`  File "/Library/Python/2.7/site-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 457, in writeUShort
    assert 0 <= value < 0x10000, value`

When I strip out all the OpenType code, the process works correctly. Any idea what is causing this?

**Comment by adrientetar** [comment]
I get the same traceback on certain fonts when writing LookupListIndex in the GSUB table, here's a full traceback:

```
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\fontView.py", line 968, in exportFile
    otf.save(path)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\__init__.py", line 202, in save
    self._writeTable(tag, writer, done)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\__init__.py", line 631, in _writeTable
    tabledata = self.getTableData(tag)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\__init__.py", line 644, in getTableData
    return self.tables[tag].compile(self)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 86, in compile
    self.table.compile(writer, font)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 679, in compile
    conv.write(writer, font, table, value)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otConverters.py", line 353, in write
    value.compile(subWriter, font)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 659, in compile
    conv.writeArray(writer, font, table, value)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otConverters.py", line 123, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otConverters.py", line 353, in write
    value.compile(subWriter, font)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 659, in compile
    conv.writeArray(writer, font, table, value)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otConverters.py", line 123, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otConverters.py", line 353, in write
    value.compile(subWriter, font)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 659, in compile
    conv.writeArray(writer, font, table, value)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otConverters.py", line 123, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otConverters.py", line 277, in write
    value.compile(writer, font)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 679, in compile
    conv.write(writer, font, table, value)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otConverters.py", line 175, in write
    writer.writeUShort(value)
  File "C:\Python34\lib\site-packages\fonttools-3.0-py3.4.egg\fontTools\ttLib\tables\otBase.py", line 457, in writeUShort
    assert 0 <= value < 0x10000, value
TypeError: unorderable types: int() <= NoneType()
```

cc @brawer

**Comment by behdad** [comment]
That error means an attribute that should be set to an integer, isn't set on the object.  I'll try adding some debug info that shows which object is missing it, so we can easily see what's missing.

**Comment by adrientetar** [comment]
@behdad With your patch, I get:

```
TypeError: ('unorderable types: int() <= NoneType()', 'LookupListIndex', 'SubstLookupRecord', 'ChainContextSubst', 'Lookup', 'LookupList')
```

**Comment by behdad** [comment]
Yes, that's what I got as well, but then ran out of battery!  Just back now and debugging.  It means feaLib is not setting the LookupListIndex..  Investigating.  cc @brawer

**Comment by behdad** [comment]
Here's a patch that I think is correct, but @brawer should confirm what he intended there.  In particular, there's a test that will fail with the patch, which concerns me, because I was under the impression that @brawer added expected-TTX for the tests comparing to what makeotf does, so he needs to investigate this one.
```
diff --git a/Lib/fontTools/feaLib/builder.py b/Lib/fontTools/feaLib/builder.py
index be6c7f4..75907a5 100644
--- a/Lib/fontTools/feaLib/builder.py
+++ b/Lib/fontTools/feaLib/builder.py
@@ -791,7 +791,7 @@ class ChainContextPosBuilder(LookupBuilder):
             st.PosCount = len([l for l in lookups if l is not None])
             st.PosLookupRecord = []
             for sequenceIndex, l in enumerate(lookups):
-                if l is not None:
+                if l.lookup_index is not None:
                     rec = otTables.PosLookupRecord()
                     rec.SequenceIndex = sequenceIndex
                     rec.LookupListIndex = l.lookup_index
@@ -821,7 +821,7 @@ class ChainContextSubstBuilder(LookupBuilder):
             st.SubstCount = len([l for l in lookups if l is not None])
             st.SubstLookupRecord = []
             for sequenceIndex, l in enumerate(lookups):
-                if l is not None:
+                if l.lookup_index is not None:
                     rec = otTables.SubstLookupRecord()
                     rec.SequenceIndex = sequenceIndex
                     rec.LookupListIndex = l.lookup_index
```

**Comment by brawer** [comment]
@adrientetar, would you mind making a minimal feature file (perhaps 3-5 lines) that triggers this bug? The patch looks a little suspicious to me, but it’s hard to say without a concrete test case.

**Comment by adrientetar** [comment]
@brawer:

```
feature ordn {
    sub [zero one two three four five six seven eight nine] [A a]' by ordfeminine;
    sub [zero one two three four five six seven eight nine] [O o]' by ordmasculine;
} ordn;
```

**Comment by adrientetar** [comment]
Interesting: if I remove the second substitution instruction in the feature, it doesn't crash.

**Comment by brawer** [comment]
Thanks for the report, and especially for the test case! Fixed.
