### ISSUE TITLE
[merge] Exception: Don't know how to merge key Format of class ClassDef

### ISSUE THREAD

**Issue by anthrotype** [behdad/fonttools#475]
I think it might be related to this commit: 6851f66d1810a4d3f484f2a82e39960e1a677f42 

```
$ pyftmerge --verbose --timing font1.ttf font2.ttf
Merged 'cmap'.
Took 0.010s to merge 'cmap'
Merged 'GSUB'.
Took 0.000s to merge 'GSUB'
Merged 'post'.
Took 0.000s to merge 'post'
Don't know how to merge 'VDMX'.
Dropped 'VDMX'.
Took 0.002s to merge 'VDMX'
Merged 'GPOS'.
Took 0.000s to merge 'GPOS'
Merged 'maxp'.
Took 0.000s to merge 'maxp'
Merged 'prep'.
Took 0.000s to merge 'prep'
Merged 'fpgm'.
Took 0.000s to merge 'fpgm'
Merged 'hmtx'.
Took 0.000s to merge 'hmtx'
Merged 'glyf'.
Took 0.001s to merge 'glyf'
Merged 'OS/2'.
Took 0.001s to merge 'OS/2'
Merged 'head'.
Took 0.000s to merge 'head'
Merged 'gasp'.
Took 0.000s to merge 'gasp'
Merged 'loca'.
Took 0.000s to merge 'loca'
Merged 'hhea'.
Took 0.000s to merge 'hhea'
Traceback (most recent call last):
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/merge.py", line 106, in mergeObjects
    mergeLogic = logic[key]
KeyError: 'Format'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/merge.py", line 109, in mergeObjects
    mergeLogic = logic['*']
KeyError: '*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/fonttools35/bin/pyftmerge", line 9, in <module>
    load_entry_point('fonttools', 'console_scripts', 'pyftmerge')()
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/merge.py", line 773, in merge
    table = clazz(tag).merge(self, tables)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/merge.py", line 153, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/merge.py", line 819, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/merge.py", line 115, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in lst)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/merge.py", line 112, in mergeObjects
    (key, clazz.__name__))
Exception: Don't know how to merge key Format of class ClassDef
```

**Comment by behdad** [comment]
> I think it might be related to this commit: 6851f66

I think so.  Since compositor was fixed, I reverted that.

Also, can you perhaps add a couple of tests for the merger and subsetter?  Using Noto or some other Open Source font?  Thanks!
