### ISSUE TITLE
AssertionError when try to access _ttf['name']

### ISSUE THREAD

**Issue by dns-admin** [behdad/fonttools#525]
code is simple:

```
from fontTools.ttLib import TTFont

if __name__ == '__main__':
	_ttf = TTFont('test.ttf')
	print _ttf['name']
```

```
Traceback (most recent call last):
  File "font.py", line 127, in <module>
    print _ttf['name']
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\ttLib\__init__.py", line 414, in __getitem__
    table.decompile(data, self)
  File "C:\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\ttLib\tables\_n_a_m_e.py", line 44, in decompile
    assert len(name.string) == name.length
AssertionError
```

Please rename the attached files to 'test.ttf'.
![test](https://cloud.githubusercontent.com/assets/3537742/13075389/c59cf90c-d4e5-11e5-9c9e-a17510b2720d.jpg)

**Comment by brawer** [comment]
The attachment is a JPEG image; can you attach the failing font?

**Comment by dns-admin** [comment]
doed any one see the last words? no ttf file is allowed to be uploded, so i renamed to a jpeg.
