### ISSUE TITLE
Traceback in getOverflowErrorRecord()

### ISSUE THREAD

**Issue by justvanrossum** [behdad/fonttools#537]
This is after adding a big kern feature with feaLib.builder.addOpenTypeFeatures(). I'll gladly provide source data, but it'll have to be private I'm afraid. Does anyone have experience with this? I'll gladly investigate further, but I'm stuck at the moment.
```
Traceback (most recent call last):
  File "/Users/just/code/git/vanilla/Lib/vanilla/dialogs.py", line 110, in savePanelDidEnd_returnCode_contextInfo_
    self._resultCallback(self._result)
  File "GenerateFontWithProblemKerning.py", line 38, in compileCallback
  File "GenerateFontWithProblemKerning.py", line 21, in addKerningToGeneratedFont
  File "/Users/just/code/git/fonttools/Lib/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Users/just/code/git/fonttools/Lib/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/just/code/git/fonttools/Lib/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/just/code/git/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 90, in compile
    return writer.getAllData()
  File "/Users/just/code/git/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 269, in getAllData
    tableData = table.getData()
  File "/Users/just/code/git/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 337, in getData
    overflowErrorRecord = self.getOverflowErrorRecord(item)
  File "/Users/just/code/git/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 509, in getOverflowErrorRecord
    itemName = item.name
AttributeError: 'str' object has no attribute 'name'
```

**Comment by brawer** [comment]
Mind sending the feature file (and the font to which it’s being added) to sascha@brawer.ch? I’ll have a look.

**Comment by behdad** [comment]
Please send to me as well.  I don't think wr have subtablesplitting for gpos lookups implemented.

**Comment by justvanrossum** [comment]
Indeed you're right, I somehow misremembered what is and is not supported. The exception I'm getting is rather weird, though. I sent you both the data, FWIW.

**Comment by behdad** [comment]
Ok, I'm finally making progress after having been stuck on it for a week.

My table split logic was solid.  But I was seeing another offset overflow, in ClassDef2, with my change.  So I thought something else isn't working.  But now I see what's happening: now it's the table sharing that is causing overflow, when it tries to merge two identical ClassDef2's where they are two far away.  Working on fixing that.

**Comment by behdad** [comment]
FWIW, here's a tiny patch that disables table sharing.  It will make your font compile, while I work on a proper fix, which I expect to take a while.  It's trickiest part of the codebase...

```
diff --git a/Lib/fontTools/ttLib/tables/otBase.py b/Lib/fontTools/ttLib/tables/otBase.py
index bededbd..a51649d 100644
--- a/Lib/fontTools/ttLib/tables/otBase.py
+++ b/Lib/fontTools/ttLib/tables/otBase.py
@@ -310,6 +310,7 @@ class OTTableWriter(object):
 		# empty, array.  So, we don't share those.
 		# See: https://github.com/behdad/fonttools/issues/518
 		dontShare = hasattr(self, 'DontShare')
+		dontShare = True
 
 		if isExtension:
 			internedTables = {}
```

**Comment by justvanrossum** [comment]
Wow, thanks! (Interesting how making the result more bloaty seems to get fewer overflows...)

**Comment by behdad** [comment]
What's happening is this: we have huge PairPosFormat2 table, which is so big the offset for all its members overflow as the main struct itself is over 64k.  So we split it in two, in my newly added splitPairPos().  Now we have two subtables that are small enough that they won't overflow if the each encode their Coverage, Class1Def, and Class2Def right after themselves.  However, because of the we split (and I cannot think of any other way anyway), the two split subtables have the exact same Class2Def.  So the first subtable tries to reuse the second subtable's Class2Def, which means it will definitely overflow, since the sum of the two subtables' length is about the same as the original overflowing subtable...

So, I need to rewrite the table serialization to only reuse an exact same table if the offset won't overflow...

**Comment by behdad** [comment]
Fortunately, we can disable sharing selectively, so this is fixed now :)

**Comment by anthrotype** [comment]
I pulled the latest commit c6facc9, then used `./apply-feature-file.py -v features font.ttf font2.ttf` on Source Sans Pro and this time it compiled. However, if I then roundtrip the generated "font2.ttf" using ttx, I get this error when compiling "font2.ttx" to "font2#1.ttf":

```
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttx.py", line 383, in main
    process(jobs, options)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttx.py", line 356, in process
    action(input, output, options)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/misc/loggingTools.py", line 369, in wrapper
    return func(*args, **kwds)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttx.py", line 277, in ttCompile
    ttf.save(output)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 108, in compile
    ok = fixSubTableOverFlows(font, overflowRecord)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/tables/otTables.py", line 801, in fixSubTableOverFlows
    ok = splitFunc(subtable, newSubTable, overflowRecord)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/tables/otTables.py", line 701, in splitPairPos
    if oldSubTable.Format == 2 and oldSubTable.Class1Count > 1:
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 543, in __getattr__
    raise AttributeError(attr)
AttributeError: Class1Count
```

**Comment by justvanrossum** [comment]
Compiling works fine for my test fonts at the moment. Thanks @behdad! But I get the same Class1Count exception when roundtripping with ttx.

**Comment by behdad** [comment]
Will take a look tomorrow.

**Comment by behdad** [comment]
Fixed.  Note that roundtripping splits the tables into smaller ones, so, don't rely on it.  I might try fixing that too.

**Comment by behdad** [comment]
Should be better now.
