### ISSUE TITLE
[feaLib] OTLOffsetOverflowError with Source Sans Pro

### ISSUE THREAD

**Issue by khaledhosny** [behdad/fonttools#567]
I’m getting an `OTLOffsetOverflowError` when applying Source Sans Pro features with feaLib. Going to https://github.com/adobe-fonts/source-sans-pro/tree/master/Roman/Regular and calling:
````
apply-feature-file.py features font.ttf font2.ttf
````
Gives me:
````
Traceback (most recent call last):
  File "/fonttools/Snippets/fontTools/ttLib/tables/otBase.py", line 277, in getData
    items[i] = packUShort(item.pos - pos)
  File "/fonttools/Snippets/fontTools/ttLib/tables/otBase.py", line 522, in packUShort
    return struct.pack(">H", value)
struct.error: 'H' format requires 0 <= number <= 65535

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fonttools/Snippets/apply-feature-file.py", line 19, in <module>
    font.save(outputFontPath)
  File "/fonts/fonttools/Snippets/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/fonttools/Snippets/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/fonttools/Snippets/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/fonttools/Snippets/fontTools/ttLib/tables/otBase.py", line 91, in compile
    return writer.getAllData()
  File "/fonttools/Snippets/fontTools/ttLib/tables/otBase.py", line 408, in getAllData
    tableData = table.getData()
  File "/fonttools/Snippets/fontTools/ttLib/tables/otBase.py", line 282, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
````

**Comment by khaledhosny** [comment]
(you will need #566 for hhea support, now you know why I was randomly sending patches for adding tables support).

**Comment by khaledhosny** [comment]
It seems that feaLib silently ignores the `subtable` statements, was the intent that FontTools automatically fix the overflow?

**Comment by anthrotype** [comment]
I just added a `--verbose` option to the script to set the logging level.
I see it's attempting to fix the overflow but then it fails:

```
compiling 'GPOS' table
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'Coverage', 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
Traceback (most recent call last):
  File "/Users/cosimolupo/Documents/Github/fonttools/Snippets/apply-feature-file.py", line 31, in <module>
    font.save(options.output_font)
  File "/Users/cosimolupo/Documents/Github/fonttools/Snippets/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Users/cosimolupo/Documents/Github/fonttools/Snippets/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/cosimolupo/Documents/Github/fonttools/Snippets/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/cosimolupo/Documents/Github/fonttools/Snippets/fontTools/ttLib/tables/otBase.py", line 91, in compile
    return writer.getAllData()
  File "/Users/cosimolupo/Documents/Github/fonttools/Snippets/fontTools/ttLib/tables/otBase.py", line 408, in getAllData
    tableData = table.getData()
  File "/Users/cosimolupo/Documents/Github/fonttools/Snippets/fontTools/ttLib/tables/otBase.py", line 282, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GPOS', 'LookupIndex:', 10, 'SubTableIndex:', 1, 'ItemName:', 'ClassDef2', 'ItemIndex:', None)
```

**Comment by anthrotype** [comment]
I'm not sure if this is related or not: https://github.com/behdad/fonttools/issues/537

**Comment by anthrotype** [comment]
yeah, it seems like it.
If I apply @behdad's temporary patch in https://github.com/behdad/fonttools/issues/537#issuecomment-196044531, the font then compiles.

**Comment by behdad** [comment]
Yeah, it's the same.  I have to rewrite the assembler completely and come up with heuristics to de-dedup tables upon overflow.  Will keep thinking about it.

**Comment by adrientetar** [comment]
That's going to be problematic and it doesn't look like something that will be fixed soon/easily. Maybe table sharing should be disabled by default, or fontTools should retry with table sharing disabled in case of failure.

**Comment by behdad** [comment]
> That's going to be problematic

It is.

> and it doesn't look like something that will be fixed soon/easily.

What makes you think so? :)  I aim to have it done in the next 6 weeks.  If that doesn't happen, I'll offload it to you ;).

> Maybe table sharing should be disabled by default, or fontTools should retry with table sharing disabled in case of failure.

That's one way to do it indeed.

**Comment by behdad** [comment]
Oh, I think I have a quick solution for the case of kerning that is the issue here.  Let me try.

**Comment by behdad** [comment]
Let's continue in https://github.com/behdad/fonttools/issues/537

**Comment by behdad** [comment]
Should be fixed!
