### ISSUE TITLE
Error on .ttx to .ttf (GSUB)

### ISSUE THREAD

**Issue by CiralaDevelopment** [behdad/fonttools#596]
When trying to compile my .ttx file I get an error immediately after the compiler has reached the GSUB table. 

```
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Parsing 'kern' table...
Parsing 'name' table...
Parsing 'post' table...
Parsing 'gasp' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Traceback (most recent call last):
  File "/usr/local/bin/ttx", line 11, in <module>
    ttx.main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttx.py", line 303, in main
    process(jobs, options)
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttx.py", line 288, in process
    action(input, output, options)
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttx.py", line 191, in ttCompile
    ttf.save(output)
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 200, in save
    self._writeTable(tag, writer, done)
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 596, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 608, in getTableData
    return self.tables[tag].compile(self)
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttLib/tables/_k_e_r_n.py", line 59, in compile
    data = data + subtable.compile(ttFont)
  File "/Library/Python/2.7/site-packages/FontTools/fontTools/ttLib/tables/_k_e_r_n.py", line 118, in compile
    data = struct.pack(">HHHH", nPairs, searchRange, entrySelector, rangeShift)
struct.error: integer out of range for 'H' format code
```

I have no experience with working with font files so I don't know whether this is an error with my installation or my font file, hence do I ask here. The GSUB table looks like this:

```
<GSUB>
    <Version value="1.0"/>
    <ScriptList>
      <!-- ScriptCount=1 -->
      <ScriptRecord index="0">
        <ScriptTag value="DFLT"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=0 -->
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
    </ScriptList>
    <FeatureList>
      <!-- FeatureCount=0 -->
    </FeatureList>
    <LookupList>
      <!-- LookupCount=0 -->
    </LookupList>
  </GSUB>
```

**Comment by anthrotype** [comment]
@vegancow the error does not have to do with the `GSUB` table. It is raised while compiling the `kern` table. It looks like the latter might be faulty (e.g. contains too many kern pairs).

**Comment by vegancow** [comment]
@anthrotype Ok, will look into it. Thanks!
