### ISSUE TITLE
Failure in processing oriya.ttf

### ISSUE THREAD

**Issue by khaledhosny** [behdad/fonttools#604]
TTX fails with oriya.ttf font from http://www.indlinux.org/downloads/files/indic-otf-0.2.tar.gz. It might be a broken font, but just in case someone can look into it.

**Comment by anthrotype** [comment]
Do you mind attaching the full traceback? Thanks

**Comment by khaledhosny** [comment]
I meant to post it in the report but I missed it:
```
scribus-ctl (ctl % u=)$ ttx -o o.ttx indic/OpenType/oriya.ttf 
Dumping "indic/OpenType/oriya.ttf" to "o.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "fonttools/Lib/fontTools/ttx.py", line 383, in main
    process(jobs, options)
  File "fonttools/Lib/fontTools/ttx.py", line 356, in process
    action(input, output, options)
  File "fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "fonttools/Lib/fontTools/ttx.py", line 256, in ttDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "fonttools/Lib/fontTools/ttLib/__init__.py", line 302, in saveXML
    self._tableToXML(tableWriter, tag, progress)
  File "fonttools/Lib/fontTools/ttLib/__init__.py", line 340, in _tableToXML
    table.toXML(writer, self)
  File "fonttools/Lib/fontTools/ttLib/tables/_h_m_t_x.py", line 82, in toXML
    advance, sb = self.metrics[glyphName]
ValueError: need more than 0 values to unpack
```

**Comment by khaledhosny** [comment]
It seems to be a case of too short hmtx table, `hhea.numberOfHMetrics` is 116, bit the size of the the `hmtx` table is 460 = 115 × 4, so the entry for the last glyph is missing. I think the code should detect that and stop earlier with a more clear error message.

**Comment by justvanrossum** [comment]
Yeah, somewhere around line 26, most likely.

**Comment by khaledhosny** [comment]
Or may be the number of glyphs is wrong and there is actually only 115 glyphs in the font, as suggested by FontForge warning when I open the font with it:
> Bad glyph (115), its data length is negative
