### ISSUE TITLE
subsetter: CFF fonts with encoding cause error when subset

### ISSUE THREAD

**Issue by justanotherfoundry** [behdad/fonttools#620]
I got an error whenever subsetting a CFF font that has an encoding in the CFF table. To reproduce, you can use an OTF from http://justanotherfoundry.com/zalamander/JAF_Zalamander_Caps.zip

Not sure what this encoding is about, and how it got in there – these fonts are pretty ancient and were produced with the FDK in 2006.

The solution in my case was pretty easy, just deleting the encoding like this:
```
cffName = font['CFF '].cff.fontNames[0]
del font['CFF '].cff[cffName].rawDict['Encoding']
```
If the encoding is not necessary anyway the subsetter could simply delete it by default?

**Comment by adrientetar** [comment]
Please post the traceback when reporting an issue. Here it is:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyftsubset", line 9, in <module>
    load_entry_point('fonttools', 'console_scripts', 'pyftsubset')()
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/subset/__init__.py", line 2939, in main
    save_font(font, outfile, options)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/subset/__init__.py", line 2799, in save_font
    font.save(outfile, reorderTables=options.canonical_order)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/ttLib/__init__.py", line 648, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/ttLib/__init__.py", line 659, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/ttLib/tables/C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 66, in compile
    topCompiler = self.topDictIndex.getCompiler(strings, None)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 357, in getCompiler
    return self.compilerClass(self, strings, parent)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 182, in __init__
    self.items = self.getItems(items, strings)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 239, in getItems
    out.append(item.getCompiler(strings, self))
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 1483, in getCompiler
    return self.compilerClass(self, strings, parent)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 1317, in __init__
    value = getattr(dictObj, name, None)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 1492, in __getattr__
    value = conv.read(self, value)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 972, in read
    parent.strings)
  File "/Users/adrientetar/Downloads/trufont/src/fonttools/Lib/fontTools/cffLib.py", line 1020, in parseEncoding0
    encoding[code] = charset[glyphID]
IndexError: list index out of range
```

**Comment by adrientetar** [comment]
Alright, I've been tracing this. Basically, [subset.__init__](https://github.com/behdad/fonttools/blob/04c19fda809496249db9858fed6bf14a2f46ea2f/Lib/fontTools/subset/__init__.py#L1885) is truncating font.charset (glyphOrder) to the subset but then [parseEncoding](https://github.com/behdad/fonttools/blob/04c19fda809496249db9858fed6bf14a2f46ea2f/Lib/fontTools/cffLib.py#L1014) reads the number of GIDs from the original file hence the out of range. 
@behdad any pointers on how to properly fix this?

**Comment by adrientetar** [comment]
Setting `nCodes = len(charset) - 1` makes it works, the question is more of when we want to use data in the memory vs. read things from the file.

**Comment by behdad** [comment]
Humm.  It's a problem if after subsetting and upon saving we start loading data from file.  Let me reproduce and debug.
